In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import pandas as pd
data=pd.read_csv("/kaggle/input/beginner-datasets/beginner_datasets/diabetes.csv")
print(data)

     Number of times pregnant  \
0                           6   
1                           1   
2                           8   
3                           1   
4                           0   
..                        ...   
763                        10   
764                         2   
765                         5   
766                         1   
767                         1   

     Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                                  148                          
1                                                   85                          
2                                                  183                          
3                                                   89                          
4                                                  137                          
..                                                 ...                          
763                                 

In [2]:
data.head()

Number of times pregnant  \
0                         6   
1                         1   
2                         8   
3                         1   
4                         0   

   Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                                148                          
1                                                 85                          
2                                                183                          
3                                                 89                          
4                                                137                          

   Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
0                                72                                35   
1                                66                                29   
2                                64                                 0   
3                                66                                23   
4                                40                                35   

   2-Hour serum insulin (mu U/ml)  \
0                               0   
1                               0   
2                               0   
3                              94   
4                             168   

   Body mass index (weight in kg/(height in m)^2)  Diabetes pedigree function  \
0                                            33.6                       0.627   
1                                            26.6                       0.351   
2                                            23.3                       0.672   
3                                            28.1                       0.167   
4                                            43.1                       2.288   

   Age (years)  Class variable  
0           50               1  
1           31               0  
2           32               1  
3           21               0  
4           33               1

In [3]:
data.max()

Number of times pregnant                                                     17.00
Plasma glucose concentration a 2 hours in an oral glucose tolerance test    199.00
Diastolic blood pressure (mm Hg)                                            122.00
Triceps skin fold thickness (mm)                                             99.00
2-Hour serum insulin (mu U/ml)                                              846.00
Body mass index (weight in kg/(height in m)^2)                               67.10
Diabetes pedigree function                                                    2.42
Age (years)                                                                  81.00
Class variable                                                                1.00
dtype: float64

In [4]:
data.min()

Number of times pregnant                                                     0.000
Plasma glucose concentration a 2 hours in an oral glucose tolerance test     0.000
Diastolic blood pressure (mm Hg)                                             0.000
Triceps skin fold thickness (mm)                                             0.000
2-Hour serum insulin (mu U/ml)                                               0.000
Body mass index (weight in kg/(height in m)^2)                               0.000
Diabetes pedigree function                                                   0.078
Age (years)                                                                 21.000
Class variable                                                               0.000
dtype: float64

In [5]:
data.std()

Number of times pregnant                                                      3.369578
Plasma glucose concentration a 2 hours in an oral glucose tolerance test     31.972618
Diastolic blood pressure (mm Hg)                                             19.355807
Triceps skin fold thickness (mm)                                             15.952218
2-Hour serum insulin (mu U/ml)                                              115.244002
Body mass index (weight in kg/(height in m)^2)                                7.884160
Diabetes pedigree function                                                    0.331329
Age (years)                                                                  11.760232
Class variable                                                                0.476951
dtype: float64

In [6]:
Norm_L1_Data=preprocessing.normalize(input_data,norm='l1')
print(Norm_L1_Data)

NameError: name 'preprocessing' is not defined

In [10]:
import numpy as hp
from sklearn import preprocessing


In [14]:
binary_data=preprocessing.Binarizer(threshold=100).transform(data)
print(binary_data)

[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but Binarizer was fitted without feature names
  warnings.warn(


In [18]:
data = data.iloc[:,2:]

In [19]:
data.shape

(768, 1)

In [21]:
import matplotlib.pyplot as plt
plt.scatter(data['Number of times pregnant'],data['Plasma glucose concentration a 2 hours in an oral glucose tolerance test'],data['Diastolic blood pressure (mm Hg)'],
           data['Triceps skin fold thickness (mm)'],data['2-Hour serum insulin (mu U/ml)'],c = data['Diabetes pedigree function'])

KeyError: 'Number of times pregnant'

In [26]:
Minmax_Data=preprocessing.MinMaxScaler(feature_range=(2,15)).fit_transform(data)
print(Minmax_Data)

[[15.]
 [ 2.]
 [15.]
 [ 2.]
 [15.]
 [ 2.]
 [15.]
 [ 2.]
 [15.]
 [15.]
 [ 2.]
 [15.]
 [ 2.]
 [15.]
 [15.]
 [15.]
 [15.]
 [15.]
 [ 2.]
 [15.]
 [ 2.]
 [ 2.]
 [15.]
 [15.]
 [15.]
 [15.]
 [15.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [15.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [15.]
 [15.]
 [15.]
 [ 2.]
 [ 2.]
 [ 2.]
 [15.]
 [ 2.]
 [15.]
 [ 2.]
 [ 2.]
 [15.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [15.]
 [ 2.]
 [ 2.]
 [15.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [15.]
 [ 2.]
 [ 2.]
 [15.]
 [ 2.]
 [15.]
 [ 2.]
 [ 2.]
 [ 2.]
 [15.]
 [ 2.]
 [15.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [15.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [15.]
 [ 2.]
 [ 2.]
 [ 2.]
 [15.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [15.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [15.]
 [15.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [15.]
 [15.]
 [15.]
 [ 2.]
 [ 2.]
 [15.]
 [15.]
 [15.]
 [ 2.]
 [ 2.]
 [ 2.]
 [15.]
 [ 2.]
 [ 2.]
 [ 2.]
 [15.]
 [15.]
 [ 2.]
 [ 2.]
 [15.]
 [15.]
 [15.]
 [15.]
 [15.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]

In [27]:
Norm_L1_Data=preprocessing.normalize(data,norm='l1')
print(Norm_L1_Data)

[[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.

In [28]:
Norm_L2_Data=preprocessing.normalize(data,norm='l2')
print(Norm_L2_Data)

[[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.