In [7]:
import numpy as np
import pandas as pd

In [8]:
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [9]:
X,y = make_classification(n_samples = 10000, n_features=10, n_informative=3)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
y_pred = dt.predict(X_test)
print("Decision Tree accuracy",accuracy_score(y_test,y_pred))

Decision Tree accuracy 0.911


# **Bagging**

In [13]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
)

bag.fit(X_train,y_train)
y_pred = bag.predict(X_test)
print("Bagging classifier accuracy",accuracy_score(y_test,y_pred))


Bagging classifier accuracy 0.935


In [15]:
bag.estimators_samples_

[array([5625, 3533,  412, ...,   36, 4778, 2841]),
 array([ 627, 5215, 6241, ..., 6879, 3750, 2836]),
 array([1620, 7297, 2165, ..., 2872, 4112, 1158]),
 array([6770, 3415, 6447, ..., 7818,   45, 1728]),
 array([ 669,  592, 7651, ..., 3940,  386,   61]),
 array([1226, 6726, 2959, ..., 3299, 5925, 4222]),
 array([1250, 7018, 1972, ..., 7280, 1241, 2483]),
 array([6742, 1996, 2947, ..., 7110, 1470, 6071]),
 array([4448, 4005, 1692, ..., 2717, 5224, 4397]),
 array([2953, 2100, 6424, ..., 1212, 5683, 2954]),
 array([4211,  934, 4211, ..., 4550, 1694, 7163]),
 array([5055, 4724, 3493, ..., 1243, 7287, 3555]),
 array([4199, 3836, 2146, ..., 4175, 1816, 2958]),
 array([4992, 5124, 1859, ..., 3327, 6755, 4343]),
 array([5056, 7263, 2111, ..., 2447, 3360,  425]),
 array([4154, 6433, 7447, ..., 4960, 4736, 2053]),
 array([2494, 7476, 6337, ..., 6011,  565, 5269]),
 array([5713, 7748, 4859, ..., 5299, 5005, 1621]),
 array([6701, 7206, 6705, ..., 2882,  675, 4970]),
 array([4158, 6450, 6607, ..., 

In [16]:
bag.estimators_samples_[0]

array([5625, 3533,  412, ...,   36, 4778, 2841])

In [17]:
bag.estimators_samples_[0].shape

(2000,)

# **Bagging Using SVM**

In [18]:
bag = BaggingClassifier(
    estimator=SVC(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
)

bag.fit(X_train,y_train)
y_pred = bag.predict(X_test)
print("Bagging classifier accuracy",accuracy_score(y_test,y_pred))

Bagging classifier accuracy 0.888


# **Pasting**

In [19]:
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=False,
    random_state=42,
    verbose=1,
    n_jobs=-1
)

bag.fit(X_train,y_train)
y_pred = bag.predict(X_test)
print("Bagging classifier accuracy",accuracy_score(y_test,y_pred))

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    8.5s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


Bagging classifier accuracy 0.935


[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    0.2s finished


# **Random Subspaces**

In [20]:
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=1.0,
    max_features=0.5,
    bootstrap_features=True,
    random_state=42,
)

bag.fit(X_train,y_train)
y_pred = bag.predict(X_test)
print("Bagging classifier accuracy",accuracy_score(y_test,y_pred))

Bagging classifier accuracy 0.926


# **Random Patches**

In [22]:
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=0.25,
    max_features=0.5,
    bootstrap_features=True,
    bootstrap =True,
    random_state=42,
)

bag.fit(X_train,y_train)
y_pred = bag.predict(X_test)
print("Bagging classifier accuracy",accuracy_score(y_test,y_pred))

Bagging classifier accuracy 0.918


# **OOB score (Out of Bag Sample)**

In [23]:
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
    oob_score=True,
    random_state=42,
)

bag.fit(X_train,y_train)
y_pred = bag.predict(X_test)
print("Bagging classifier accuracy",accuracy_score(y_test,y_pred))

Bagging classifier accuracy 0.937


In [25]:
bag.oob_score_

0.937625

# **Applying GridSearchCV(How to find best result)**

In [28]:
from sklearn.model_selection import GridSearchCV
parameters = {
    'n_estimators' : [50,100,500],
    'max_samples' : [0.1,0.4,0.7,1.0],
    'bootstrap' : [True,False],
    'max_features' : [0.1,0.4,0.7,1.0]
}


In [ ]:
search = GridSearchCV(BaggingClassifier(),parameters,cv=5)
search.fit(X_train,y_train)
search.best_params_

In [ ]:
search.best_params_